{% set name = "hjson-py" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/hjson/hjson-{{ version }}.tar.gz
  sha256: 55af475a27cf83a7969c808399d7bccdec8fb836a07ddbd574587593b9cdcf75

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - hjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/hjson/hjson-py
  summary: Hjson, a user interface for JSON.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - weiji14
